FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y 
RUN apt-get install -y apache2
RUN apt-get install -y php8.2
RUN apt-get install -y libapache2-mod-php8.2


ENV APACHE_DOCUMENT_ROOT=/var/www/html


COPY ./index.php ${APACHE_DOCUMENT_ROOT}/index.php

CMD ["apache2ctl", "-D", "FOREGROUND"]

LABEL maintainer="Andrew DL"
LABEL description="Dockerfile for Ubuntu 22.04, Apache 2.4 and PHP 8.2"

